# Note: language code below should be understood as
#       language code proper with region code (if it exists)
#       (eg. en-US)

# Supported language means that
# there is a langpack matching its language code -
# it does not imply availability of a helppack
# for that language.
supported_langs = {
    "af": "Afrikaans",
    "am": "Amharic",
    "ar": "Arabic",
    "as": "Assamese",
    "ast": "Asturian",
    "be": "Belarusian",
    "bg": "Bulgarian",
    "bn": "Bengali",
    "bn-IN": "Bengali (India)",
    "bo": "Tibetan (PR China)",
    "br": "Breton",
    "brx": "Bodo (India)",
    "bs": "Bosnian",
    "ca": "Catalan",
    "ca-valencia": "Catalan (Valencian)",
    "ckb": "Kurdish (Central)",
    "cs": "Czech",
    "cy": "Welsh",
    "da": "Danish",
    "de": "German",
    "dgo": "Dogri",
    "dsb": "Sorbian (Lower)",
    "dz": "Dzongkha",
    "el": "Greek",
    "en-GB": "English (United Kingdom)",
    "en-US": "English (USA)",
    "en-ZA": "English (South Africa)",
    "eo": "Esperanto",
    "es": "Spanish",
    "et": "Estonian",
    "eu": "Basque",
    "fa": "Farsi",
    "fi": "Finnish",
    "fr": "French",
    "fur": "Friulian",
    "fy": "Frisian",
    "ga": "Gaelic (Ireland)",
    "gd": "Gaelic (Scotland)",
    "gl": "Galician",
    "gu": "Gujarati",
    "gug": "Guaraní (Paraguayan)",
    "he": "Hebrew",
    "hi": "Hindi (India)",
    "hr": "Croatian",
    "hsb": "Sorbian (Upper)",
    "hu": "Hungarian",
    "id": "Indonesian",
    "is": "Icelandic",
    "it": "Italian",
    "ja": "Japanese",
    "ka": "Georgian",
    "kab": "Kabyle",
    "kk": "Kazakh",
    "km": "Khmer",
    "kmr-Latn": "Kurdish",
    "kn": "Kannada (India)",
    "ko": "Korean",
    "kok": "Konkani",
    "ks": "Kashmiri (Kashmir)",
    "lb": "Luxembourgish",
    "lo": "Lao",
    "lt": "Lithuanian",
    "lv": "Latvian",
    "mai": "Maithili",
    "mk": "Macedonian",
    "ml": "Malayalam (India)",
    "mn": "Mongolian",
    "mni": "Manipuri",
    "mr": "Marathi (India)",
    "my": "Burmese",
    "nb": "Norwegian (Bokmaal)",
    "ne": "Nepali",
    "nl": "Dutch",
    "nn": "Norwegian (Nynorsk)",
    "nr": "Ndebele",
    "nso": "Northern Sotho",
    "oc": "Occitan",
    "om": "Oromo",
    "or": "Oriya (India)",
    "pa-IN": "Punjabi (India)",
    "pl": "Polish",
    "pt": "Portuguese (Portugal)",
    "pt-BR": "Portuguese (Brazil)",
    "ro": "Romanian",
    "ru": "Russian",
    "rw": "Kinyarwanda",
    "sa-IN": "Sanskrit (India)",
    "sat": "Santali",
    "sd": "Sindhi",
    "si": "Sinhala",
    "sid": "Sidama",
    "sk": "Slovak",
    "sl": "Slovenian",
    "sq": "Albanian",
    "sr": "Serbian",
    "sr-Latn": "Serbian Latin (Serbia)",
    "ss": "Swati",
    "st": "Sotho",
    "sv": "Swedish",
    "sw-TZ": "Swahili (Tanzania)",
    "szl": "Silesian",
    "ta": "Tamil (India)",
    "te": "Telugu (India)",
    "tg": "Tajik",
    "th": "Thai",
    "tn": "Tswana",
    "tr": "Turkish",
    "ts": "Tsonga",
    "tt": "Tatar",
    "ug": "Uyghur",
    "uk": "Ukrainian",
    "uz": "Uzbek",
    "ve": "Venda",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "xh": "Xhosa",
    "zh-CN": "Chinese (simplified)",
    "zh-TW": "Chinese (traditional)",
    "zu": "Zulu",
}

# helppacks is the list of language codes
# for which a helppack is provided.
# fmt: off
existing_helppacks = [
    "en-US", "he", "ar", "en-GB", "en-ZA", "lo", "ro", "bs", "cs",
    "da", "eo", "et", "eu", "fi", "gu", "hi", "hr", "hsb", "id", "is",
    "lv", "mk", "nb", "nn", "sid", "sl", "sq", "sv", "tg", "ug", "vi",
    "ast", "ca", "ca-valencia", "de", "dsb", "es", "fr", "gl", "it",
    "ka", "ko", "lt", "nl", "om", "pl", "pt-BR", "pt", "si", "sk",
    "tr", "zh-CN", "am", "bn", "bo", "hu", "ne", "zh-TW", "bg", "dz",
    "ru", "ta", "uk", "bn-IN", "ja", "km", "el"
    ]
# fmt: on
